client_config_backend: settings
client_config:
  client_id: 666472474471-2dsgsclntab570a4o3q7ed3u4fimearu.apps.googleusercontent.com
  client_secret: 7zst7YPrbl0jlmPQge_TfsCb

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install